// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cmwc
NumericVector cmwc(int seed, int n);
RcppExport SEXP _randngen_cmwc(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cmwc(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// icg
NumericVector icg(int q, int a, int c, int seed, int n);
RcppExport SEXP _randngen_icg(SEXP qSEXP, SEXP aSEXP, SEXP cSEXP, SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(icg(q, a, c, seed, n));
    return rcpp_result_gen;
END_RCPP
}
// lcg
NumericVector lcg(int seed, int n);
RcppExport SEXP _randngen_lcg(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lcg(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// lcg_internal
NumericVector lcg_internal(int seed, int n);
RcppExport SEXP _randngen_lcg_internal(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lcg_internal(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// lcg_parkmiller
NumericVector lcg_parkmiller(int seed, int n);
RcppExport SEXP _randngen_lcg_parkmiller(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lcg_parkmiller(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// lfg
NumericVector lfg(int seed, int n);
RcppExport SEXP _randngen_lfg(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lfg(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// lfsr
NumericVector lfsr(int seed);
RcppExport SEXP _randngen_lfsr(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(lfsr(seed));
    return rcpp_result_gen;
END_RCPP
}
// middlesquare
NumericVector middlesquare(int seed, int n);
RcppExport SEXP _randngen_middlesquare(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(middlesquare(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// mwc
NumericVector mwc(int seed, int n);
RcppExport SEXP _randngen_mwc(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mwc(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// winchmann_hill
NumericVector winchmann_hill(int seed1, int seed2, int seed3, int n);
RcppExport SEXP _randngen_winchmann_hill(SEXP seed1SEXP, SEXP seed2SEXP, SEXP seed3SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type seed1(seed1SEXP);
    Rcpp::traits::input_parameter< int >::type seed2(seed2SEXP);
    Rcpp::traits::input_parameter< int >::type seed3(seed3SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(winchmann_hill(seed1, seed2, seed3, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_randngen_cmwc", (DL_FUNC) &_randngen_cmwc, 2},
    {"_randngen_icg", (DL_FUNC) &_randngen_icg, 5},
    {"_randngen_lcg", (DL_FUNC) &_randngen_lcg, 2},
    {"_randngen_lcg_internal", (DL_FUNC) &_randngen_lcg_internal, 2},
    {"_randngen_lcg_parkmiller", (DL_FUNC) &_randngen_lcg_parkmiller, 2},
    {"_randngen_lfg", (DL_FUNC) &_randngen_lfg, 2},
    {"_randngen_lfsr", (DL_FUNC) &_randngen_lfsr, 1},
    {"_randngen_middlesquare", (DL_FUNC) &_randngen_middlesquare, 2},
    {"_randngen_mwc", (DL_FUNC) &_randngen_mwc, 2},
    {"_randngen_winchmann_hill", (DL_FUNC) &_randngen_winchmann_hill, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_randngen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
