# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmwc <- function(seed, n) {
    .Call(`_randngen_cmwc`, seed, n)
}

icg <- function(q, a, c, seed, n) {
    .Call(`_randngen_icg`, q, a, c, seed, n)
}

#' Linear Congruential Generator
#'
#'A linear congruential generator (LCG) is an algorithm that yields a sequence of pseudo-randomized numbers calculated with a discontinuous piecewise linear equation. The method represents one of the oldest and best-known pseudorandom number generator algorithms. The theory behind them is relatively easy to understand, and they are easily implemented and fast, especially on computer hardware which can provide modular arithmetic by storage-bit truncation.
#'
#'
#' The generator is defined by the recurrence relation:
#' \deqn{X_{n+1} = (aX + c) \text{ mod } m}
#' Where \eqn{X} is the sequence of pseudo-random values and
#'
#' - \eqn{m, 0 < m} - the "modulus"
#'
#' - \eqn{a, 0 < a < m} - the "multiplier"
#'
#' - \eqn{c, 0 \le c < m} - the "increment"
#'
#' - \eqn{X_0, 0 \le X_0 < m} - the "seed" or "start value"
#'
#' For more information see the \href{https://en.wikipedia.org/wiki/Linear_congruential_generator}{Wikipedia page}.
#'
#' @param seed initial starting value
#' @param n the number of random numbers you want to create.
#' @param m modulus argument. By default, \eqn{m = 2^16  + 1} (follows ZX81 configuration)
#' @param a multiplier argument. By default, \eqn{a = 75} (follows ZX81 configuration)
#' @param c increment argument By default, \eqn{c = 74} (follows ZX81 configuration)
#' @examples
#' random_numbers <- lcg(1234, 1000)
#' # Plot numbers to see that they are random
#' plot(random_numbers)
#' @export
lcg <- function(seed, n, m = 65537L, a = 75L, c = 74L) {
    .Call(`_randngen_lcg`, seed, n, m, a, c)
}

lcg_internal <- function(seed, n) {
    .Call(`_randngen_lcg_internal`, seed, n)
}

#' Park Miller Generator
#'
#' TODO: Documentation
#'
#' For more information see the \href{https://en.wikipedia.org/wiki/Lehmer_random_number_generator}{Wikipedia page}.
#'
#' @param seed initial starting value
#' @param n the number of random numbers you want to create.
#' @examples
#' random_numbers <- lcg_parkmiller(1234, 1000)
#' # Plot numbers to see that they are random
#' plot(random_numbers)
#' @export
lcg_parkmiller <- function(seed, n) {
    .Call(`_randngen_lcg_parkmiller`, seed, n)
}

lfg <- function(seed, n) {
    .Call(`_randngen_lfg`, seed, n)
}

lfsr <- function(seed) {
    .Call(`_randngen_lfsr`, seed)
}

#' Middles-Square Method
#'
#' [DESCRIPTION: TODO]
#' This code is based on the python code shared on Wikipedia ([link](https://en.wikipedia.org/wiki/Middle-square_method))
#'
#' @param seed initial starting value
#' @param n number of random numbers desired
#' @examples
#' random_numbers <- middlesquare(1234, 1000)
#' # Plot numbers to see that they are random
#' plot(random_numbers)
#' @export
middlesquare <- function(seed, n) {
    .Call(`_randngen_middlesquare`, seed, n)
}

#' Multiply With Carry (MWC)
#'
#' The multiply-with-carry (MWC) method is a method invented by \href{https://en.wikipedia.org/wiki/George_Marsaglia}{George Marsaglia} for generating sequences of random integers based on an initial set of from two to manu thousands of randomly chosent seed values. The main advantages of the MWC mehtod are that it invokes simple computer integer arithmetic and leads to very fast generation of sequences of random numbers with immense periods, ranging from around \eqn{2^{60}} to \eqn{2^{20000000}}.
#'
#' A MWC generator is a special form of a Lehmer Random Number Generator (see \code{\link{lcg_parkmiller}}) \eqn{x_n=bx_{n-1} \mod p} which allows efficient implementation of a prime modulus \eqn{p} much larger than the machine word size.
#'
#' Normal Lehmer generator implementations choose a modulsus close to the machine word size. A MWC generator instead maintains its state it base \eqn{b}, so multiplying by \eqn{b} is done implicitly by shifting one word. The base
#'
#' For more information, see the \href{https://en.wikipedia.org/wiki/Multiply-with-carry_pseudorandom_number_generator}{Wikipedia page}.
#' @param seed initial starting value
#' @param n number of random numbers desired to be generated
#' @param b by default set to \eqn{2^{32} = 4294967296}
#' @param a by default set to 7
#' @param c by default set to 4
#' @export
#' @examples
#' random_numbers <- mwc(6793,1000)
#' # Plot numbers to see that they are random
#' plot(random_numbers)
#' @export
mwc <- function(seed, n, b = 4294967296L, a = 7L, c = 4L) {
    .Call(`_randngen_mwc`, seed, n, b, a, c)
}

winchmann_hill <- function(seed1, seed2, seed3, n) {
    .Call(`_randngen_winchmann_hill`, seed1, seed2, seed3, n)
}

