# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmwc <- function(seed, n) {
    .Call(`_randngen_cmwc`, seed, n)
}

icg <- function(q, a, c, seed, n) {
    .Call(`_randngen_icg`, q, a, c, seed, n)
}

#' Linear Congruential Generator
#'
#' [TODO: WRITE DESCRIPTION]
#'
#' For more reading check out Wikipedia:https://en.wikipedia.org/wiki/Linear_congruential_generator
#'
#' @param seed initial starting value
#' @param n the number of random numbers you want to create.
#' @examples
#' random_numbers <- lcg(1234, 1000)
#' # Plot numbers to see that they are random
#' plot(random_numbers)
#' @export
lcg <- function(seed, n) {
    .Call(`_randngen_lcg`, seed, n)
}

lcg_internal <- function(seed, n) {
    .Call(`_randngen_lcg_internal`, seed, n)
}

lcg_parkmiller <- function(seed, n) {
    .Call(`_randngen_lcg_parkmiller`, seed, n)
}

lfg <- function(seed, n) {
    .Call(`_randngen_lfg`, seed, n)
}

lfsr <- function(seed) {
    .Call(`_randngen_lfsr`, seed)
}

middlesquare <- function(seed, n) {
    .Call(`_randngen_middlesquare`, seed, n)
}

mwc <- function(seed, n) {
    .Call(`_randngen_mwc`, seed, n)
}

winchmann_hill <- function(seed1, seed2, seed3, n) {
    .Call(`_randngen_winchmann_hill`, seed1, seed2, seed3, n)
}

