name: Build Package Site

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout with push rights
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Pandoc (for vignettes) and R
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # 3) System libraries: curl, ssl, xml2 *and* Boost headers
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libboost-dev

      # 4) R package dependencies
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("Rcpp","devtools","roxygen2","pkgdown"))'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      # 5) Build site into docs/
      - name: Build site
        run: Rscript -e 'devtools::build_site()'

      # 6) Commit & push only docs/ if changed
      - name: Commit and push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to docs/"
          else
            git commit -m "Rebuild site"
            git push
          fi
